config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.home.views import HomeTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeTemplateView.as_view(), name='home'),
    path('home/', include('core.home.urls')),
    path('profil/', include('core.profiles.urls')),
    path('chatbot/', include('core.chatbot.urls')),
    path('auth/', include('core.login_register.urls')),
    path('authRercPassw/', include('core.recover_password.urls')),
    path('webscraping/', include('core.webscraping.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path('profile/', views.profile, name='auth_profile'),
    path('update_profile/', views.update_profile, name='auth_update_profile'),
    path('remove_image/', views.remove_image, name='auth_remove_image'),
    path('update_contra/', views.actulizarcontra, name='auth_update_contra'),
]

core/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    # gender = models.CharField(verbose_name='Sexo',
    #                           max_length=1,
    #                           choices=(('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro Genero')),
    #                           blank=False, null=False)

    image = models.ImageField(
        verbose_name='Archive image',
        upload_to='users/',
        max_length=1024,
        blank=True,
        null=True
    )
    email = models.EmailField(verbose_name='Email', unique=True)
    USERNAME_FIELD = "email"  # cambia el login
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    def __str__(self):
        return '{}'.format(self.username)

    @property
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_image(self):
        if self.image:
            return self.image.url
        else:
            return '/static/img/usuario_anonimo.png'

core/profiles/forms.py
import os
from django.conf import settings
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from ..profiles.models import User
from django import forms
class CustomUserCreationForm(UserCreationForm):
    image = forms.ImageField(required=False)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')#, 'gender'


class CustomUserUpdateForm(UserChangeForm):
    password = None  # No incluir el campo de contraseña

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'image')
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            if not image.name.lower().endswith(('.jpg', '.jpeg', '.png')):
                raise forms.ValidationError("Por favor, sube una imagen válida (jpg, jpeg, png).")
        return image

    def save(self, commit=True):
        user = super().save(commit=False)
        image = self.cleaned_data.get('image')
        print(image)
        # Guardar la imagen antigua ANTES de que sea sobreescrita
        old_image = User.objects.get(pk=user.pk).image  # Obtiene la imagen antes de ser modificada
        print(old_image)
        print("------------------222")
        if old_image != image and old_image is None:
            # despciptar para poder eliminar la fotor de perfil
            old_image_url = old_image.url
            print(f"URL de la imagen anterior: {old_image_url}")
            print("------------------")

            # Convertimos la URL a la ruta de archivo (quitamos el /media/ del principio)
            if old_image_url.startswith('/media/'):
                #eliminar no se ocupar ya que desde la base de datos no viene con el /media/  viene asi  "users/descarga_2.jpeg"
                old_image_path = os.path.join(settings.MEDIA_ROOT, old_image_url.replace('/media/', ''))

                print(f"Ruta completa de la imagen anterior: {old_image_path}")

                # Verificar que el archivo existe y eliminar la imagen anterior
                if os.path.exists(old_image_path):
                    print(f"Eliminando la imagen anterior: {old_image_path}")
                    os.remove(old_image_path)

        if commit:
            user.save()
        return user

class RemoveProfileImageForm(forms.ModelForm):
    class Meta:
        model = User
        fields = []  # Indica que no hay campos que se mostrarán al usuario

    def save(self, commit=True):
        user = super().save(commit=False)
        # Guardar la imagen antigua ANTES de eliminarla
        old_image = user.image

        if old_image:  # Si hay una imagen existente
            old_image_path = old_image.path
            if os.path.exists(old_image_path):
                os.remove(old_image_path)

        # Establecer la imagen del perfil a `None`, lo que hará que se utilice la predeterminada en `get_image()`
        user.image = None

        if commit:
            user.save()
        return user

core/profiles/views.py
from django.shortcuts import render
from django.http import JsonResponse

# Create your views here.
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserUpdateForm, RemoveProfileImageForm


# Perfil
@login_required
def profile(request):
    data = {"title1": "UIA - Perfil",
            "title2": "Perfil de Usuario"}

    return render(request, "profile.html", data)


# Actualizar perfil
@login_required
def update_profile(request):
    data = {"title1": "UIA - Actualizar Perfil", "title2": "Actualizar Perfil"}

    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, '¡Tu perfil ha sido actualizado exitosamente!')
            return redirect('profiles:auth_profile')
        else:
            messages.error(request, 'Error en los datos del formulario.')
    else:
        form = CustomUserUpdateForm(instance=request.user)

    return render(request, 'update_profile.html', {'form': form, **data})


# Actualizar contraseña
@login_required
def actulizarcontra(request):
    # Cambiar contraseña del usuario
    data = {"title1": "CS-ACTUALIZAR", "title2": "Actualizar Contraseña"}
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        data["form"] = form
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Actualiza la sesión con la nueva contraseña
            return redirect('home:homeI')  # Redirige a la página de perfil o cualquier otra página
        else:
            messages.error(request, 'Por favor corrige los errores a continuación.', extra_tags='alert-error')
    else:
        form = PasswordChangeForm(request.user)
        data["form"] = form
    return render(request, 'contra_actualizar.html', data)



@login_required
def remove_image(request):
    data = {"title1": "CS-ACTUALIZAR", "title2": "Eliminar foto de perfil"}
    if request.method == 'POST':
        form = RemoveProfileImageForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False}, status=400)
    else:
        form = RemoveProfileImageForm(instance=request.user)
    return render(request, 'profile.html', data)

core/profiles/templates/contra_actualizar.html
{% extends 'components/base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<section class="dark:bg-principal mt-20">
    <div class="text-center" data-aos="fade" data-aos-delay="200">
            <div class="flex flex-col items-center justify-center">
                <span class="rounded-full bg-indigo-500 px-2 py-1 text-white uppercase text-sm">
                    {{ title1 }}
                </span>
            </div>
            <h1 class="dark:text-white text-4xl text-center mt-6 font-Pacifico">
                {{ title2 }}
            </h1>
            <p class="dark:text-gray-400 text-center mt-6 text-lg font-light">
                Complete el formulario para actualizar su información.
            </p>
        </div>
        <form method="post" enctype="multipart/form-data" class="space-y-6 py-4">
            {% csrf_token %}
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mx-4 lg:mx-20" data-aos="fade">
                <!-- Columna de la izquierda -->
                <div class="bg-white dark:bg-secundario rounded-3xl flex flex-col justify-center items-center p-8"
                    data-aos="fade-right" data-aos-delay="200">
                    <div class="w-[60%] text-center">
                        <h2 class="dark:text-blue-300 text-2xl text-center mt-6 font-Pacifico">Imagen Actual</h2>
                        <div id="imagenPreview" class="mt-4">
                            {% if user.get_image %}
                                    <img id="imagenSeleccionada1" src="{{ user.get_image }}" class="mx-auto d-block rounded-lg" alt="Foto de perfil">
                            {% else %}
                                <img id="imagenSeleccionada" src="{% static 'img/default_person.png' %}" class="mx-auto d-block rounded-lg" alt="Foto de perfil por defecto">
                            {% endif %}
                        </div>
                    </div>
                    <div class="text-center w-auto mt-4">
                        <label for="{{ form.imagen.id_for_label }}" class="dark:text-white font-black uppercase text-lg">{{ form.imagen.label }}</label>
                        {{ form.imagen }}
                    </div>
                </div>
                <!-- Columna de la derecha -->
                <div class="p-8 rounded-3xl dark:bg-secundario bg-white flex flex-col justify-center items-center"
                    data-aos="fade-left" data-aos-delay="200">
                        <div>
                            <div class="mb-6">
                                <label for="old_password" class="dark:text-blue-300 font-black uppercase text-lg">Contraseña Actual</label>
                                <input type="password" id="old_password" name="old_password" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" required>
                            </div>
                            <div class="mb-6">
                                <label for="id_new_password1" class="dark:text-blue-300 font-black uppercase text-lg">Nueva Contraseña</label>
                                <input type="password" id="id_new_password1" name="new_password1" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" required>
                            </div>
                            <div class="mb-6">
                                <label for="id_new_password2" class="dark:text-blue-300 font-black uppercase text-lg">Confirmar Nueva Contraseña</label>
                                <input type="password" id="id_new_password2" name="new_password2" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" required>
                            </div>
                        </div>
{#                        <div>#}
{#                            {% for field in form %}#}
{#                                <div class="mb-6">#}
{#                                    <label for="{{ field.id_for_label }}" class="dark:text-blue-300  uppercase text-lg">{{ field.label }}</label>#}
{#                                    {{ field }}#}
{#                                </div>#}
{#                            {% endfor %}#}
{#                        </div>#}

                    <div class="flex flex-col md:flex-row justify-center mt-4 w-full">
                        <button type="submit" class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full mr-0 md:mr-2 mb-2 md:mb-0 flex items-center">
                            <i class="fa-solid fa-save mr-2"></i>Guardar
                        </button>
                        <a class="bg-red-700 hover:bg-red-800 text-white py-2 px-4 rounded-full flex items-center" href="{% url 'profiles:auth_profile' %}">
                            <i class="fa-solid fa-xmark mr-2"></i>Cancelar
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

<script>
    const imagenInput = document.getElementById('{{ form.imagen.id_for_label }}');
    const imagenSeleccionada = document.getElementById('imagenSeleccionada');

    imagenInput.addEventListener('change', function() {
        const file = imagenInput.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function(e) {
                imagenSeleccionada.src = e.target.result;
            }
            reader.readAsDataURL(file);
        } else {
        }
    });
</script>

{% endblock content %}

core/profiles/templates/profile.html
{% extends 'components/base.html' %}
{% load static %}

{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<section class="dark:bg-principal mt-20">
    <div class="flex flex-col items-center justify-center">
        <span class="rounded-full bg-indigo-500 px-3 py-1 text-white uppercase text-sm">
            {{ title1 }}
        </span>
    </div>

    <!-- Título principal y descripción -->
    <div class="text-center mt-6" data-aos="fade" data-aos-delay="200">
        <h1 class="dark:text-white text-4xl font-black my-4">{{ title2 }}</h1>
        <p class="dark:text-gray-400 text-lg font-light">Visualice su información.</p>
    </div>

    <!-- Formulario -->
    <form method="post" enctype="multipart/form-data" class="space-y-6 py-8">
        {% csrf_token %}
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mx-4 lg:mx-20" data-aos="fade">

            <!-- Columna izquierda: Perfil de Usuario -->
            <div class="bg-white dark:bg-secundario rounded-xl flex flex-col justify-center items-center p-8 shadow-lg"
                 data-aos="fade-right" data-aos-delay="200">
                <h2 class="dark:text-blue-300 text-2xl font-bold mb-4">Perfil de Usuario</h2>
                <div class="w-32 h-32 rounded-full overflow-hidden mb-4">
                    <div id="imagenPreview">
                        {% if user.get_image %}
                        <img src="{{ user.get_image }}" class="w-full h-full object-cover rounded-full" alt="Foto de perfil">
                        {% else %}
                        <img src="{% static 'img/unemia.png' %}" class="w-full h-full object-cover rounded-full" alt="Foto de perfil por defecto">
                        {% endif %}
                    </div>
                </div>
                {% if user.get_image != '/static/img/usuario_anonimo.png' %}
                <button id="openModal" type="button" class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full flex items-center justify-center mb-4">
                    <i class="fa-solid fa-trash-alt mr-2"></i> Eliminar foto de perfil
                </button>
                {% endif %}
            </div>

            <!-- Columna derecha: Información del usuario -->
            <div class="bg-white dark:bg-secundario rounded-xl p-8 shadow-lg flex flex-col justify-between" data-aos="fade-left" data-aos-delay="200">
                <!-- Información del usuario en una fila -->
                <div class="grid grid-cols-2 gap-6 mb-6">
                    <div>
                        <p class="dark:text-gray-400 text-lg"><span class="text-orange-500 font-bold">Usuario:</span><br>
                            {{ user.username }}
                            {% if user.is_superuser %}
                            <span class="dark:text-green-300 text-lg font-bold"> | Administrador</span>
                            {% endif %}
                        </p>
                    </div>
                    <div>
                        <p class="dark:text-gray-400 text-lg"><span class="text-orange-500 font-bold">Nombres:</span><br>
                            {{ user.first_name }} {{ user.last_name }}
                        </p>
                    </div>
                </div>
                <!-- Correo en una fila separada -->
                <div class="mb-6">
                    <p class="dark:text-gray-400 text-xl"><span class="text-orange-500 font-bold">Correo:</span><br>
                        {% if user.email %}
                        <a href="mailto:{{ user.email }}" class="text-blue-500">{{ user.email }}</a>
                        {% else %}
                        No Registrado
                        {% endif %}
                    </p>
                </div>
                <!-- Botones centrados -->
                <div class="flex justify-center gap-4">
                    <a class="bg-blue-700 hover:bg-blue-800 text-white py-3 px-6 rounded-full flex items-center justify-center"
                       href="{% url 'profiles:auth_update_profile' %}">
                        <i class="fa-solid fa-file-pen mr-2"></i> Actualizar Datos
                    </a>
                    <a class="bg-blue-700 hover:bg-blue-800 text-white py-3 px-6 rounded-full flex items-center justify-center"
                       href="{% url 'profiles:auth_update_contra' %}">
                        <i class="fa-solid fa-key mr-2"></i> Actualizar Contraseña
                    </a>
                </div>
            </div>
        </div>
    </form>
</section>

<!-- Modal de confirmación -->
<div id="confirmModal" class="fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center hidden">
    <div class="bg-white dark:bg-gray-800 rounded-3xl p-6 shadow-lg w-full max-w-lg relative">
        <h2 class="dark:text-blue-300 text-2xl text-center mb-4 font-bold">Confirmar Eliminación</h2>
        <p class="dark:text-gray-400 text-lg mb-6">¿Está seguro de que desea eliminar su foto de perfil? Esta acción no se puede deshacer.</p>

        <!-- Imágenes en el modal con flecha en el centro -->
        <div class="flex items-center justify-center space-x-8 mb-6 relative">
            <div class="w-32 h-32 rounded-full overflow-hidden">
                <div id="modalImagePreview">
                    {% if user.get_image %}
                    <img src="{{ user.get_image }}" class="w-full h-full object-cover rounded-full" alt="Foto de perfil">
                    {% else %}
                    <img src="{% static 'img/unemia.png' %}" class="w-full h-full object-cover rounded-full" alt="Foto de perfil por defecto">
                    {% endif %}
                </div>
            </div>

            <!-- Flecha en el centro -->
            <div class="absolute text-gray-500 text-3xl">
                <i class="fa-solid fa-arrow-right"></i>
            </div>

            <div class="w-32 h-32 rounded-full overflow-hidden">
                <div id="modalImageDefault">
                    <img src="{% static 'img/usuario_anonimo.png' %}" class="w-full h-full object-cover rounded-full" alt="Foto de perfil por defecto">
                </div>
            </div>
        </div>

        <div class="flex justify-center gap-4 mb-6">
            <button id="removeImage" class="bg-red-700 hover:bg-red-800 text-white py-2 px-4 rounded-full flex items-center justify-center">
                <i class="fa-solid fa-trash-alt mr-2"></i> Eliminar
            </button>
            <button id="closeModal" class="bg-gray-500 hover:bg-gray-600 text-white py-2 px-4 rounded-full flex items-center justify-center">
                <i class="fa-solid fa-times mr-2"></i> Cancelar
            </button>
        </div>

        <!-- Botón de cerrar -->
        <button id="closeModalIcon" class="absolute top-2 right-2 text-gray-500 hover:text-gray-800">
            <i class="fa-solid fa-xmark text-2xl"></i>
        </button>
    </div>
</div>

<!-- JavaScript -->
<script>
    document.getElementById('openModal').addEventListener('click', function () {
        document.getElementById('confirmModal').classList.remove('hidden');
    });

    document.getElementById('closeModal').addEventListener('click', function () {
        document.getElementById('confirmModal').classList.add('hidden');
    });

    document.getElementById('closeModalIcon').addEventListener('click', function () {
        document.getElementById('confirmModal').classList.add('hidden');
    });

    document.getElementById('removeImage').addEventListener('click', function () {
        fetch("{% url 'profiles:auth_remove_image' %}", {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({})  // Enviar un cuerpo vacío para la solicitud POST
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Actualizar la vista de la imagen en la página
                document.getElementById('imagenPreview').innerHTML = `
                    <img src="{% static 'img/usuario_anonimo.png' %}" class="w-full h-full object-cover rounded-full" alt="Foto de perfil por defecto">
                `;
                document.getElementById('confirmModal').classList.add('hidden');
                // Redirigir a la página de perfil o mostrar un mensaje de éxito
                window.location.reload();  // Recargar la página
            } else {
                console.error('Error al eliminar la imagen.');
            }
        })
        .catch(error => console.error('Error:', error));
    });
</script>
{% endblock %}

core/profiles/templates/remove_image.html
{% extends 'components/base.html' %}
{% load static %}

{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<section class="dark:bg-principal mt-20">
    <div class="flex flex-col items-center justify-center">
        <span class="rounded-full bg-indigo-500 px-2 py-1 text-white uppercase text-sm">
            {{ title1 }}
        </span>
    </div>
    <div class="text-center" data-aos="fade" data-aos-delay="200">
        <h1 class="dark:text-white text-4xl  text-center mt-6 font-black my-2">
            {{ title2 }}
        </h1>
        <p class="dark:text-gray-400 text-center mt-6 text-lg font-light">
            Visualice su información.
        </p>
    </div>
    <form method="post" enctype="multipart/form-data" class="space-y-6 py-4">
        {% csrf_token %}
        <div class="flex justify-center mx-4 lg:mx-20" data-aos="fade">
            <!-- Columna izquierda -->
            <div class="bg-white dark:bg-secundario rounded-3xl flex flex-col justify-center items-center p-8"
                 data-aos="fade-right" data-aos-delay="200">
                <h2 class="dark:text-blue-300 text-2xl text-center mt-6 font-black my-2 mb-4">Perfil de Usuario</h2>
                <div class="flex justify-between mx-4 lg:mx-20">
                    <div class="w-[60%] text-center rounded-full overflow-hidden">
                        <div id="imagenPreview">
                            {% if user.get_image %}
                            <img src="{{ user.get_image }}" class="mx-auto d-block rounded-full" alt="Foto de perfil"
                                 style="width: 150px; height: 150px;">
                            {% else %}
                            <img src="{% static 'img/unemia.png'%}" class="mx-auto d-block rounded-full"
                                 alt="Foto de perfil por defecto" style="width: 150px; height: 150px;">
                            {% endif %}
                        </div>
                    </div>

                    <div class="dark:text-gray-400 text-center mt-6 text-lg font-light ">
                        <i class="fa-solid fa-arrow-right"></i>
                    </div>
                    <div class="w-[60%] text-center rounded-full overflow-hidden">
                        <div id="imagenDefault">
                            <img src="{% static 'img/usuario_anonimo.png'%}" class="mx-auto d-block rounded-full"
                                 alt="Foto de perfil por defecto" style="width: 150px; height: 150px;">
                        </div>

                    </div>
                </div>

                <div class="text-center" data-aos="fade" data-aos-delay="200">
                    <p class="dark:text-gray-400 text-center mt-6 text-lg font-light">
                        ¿Quieres quitar la foto de perfil?
                    </p>
                    <p class="dark:text-gray-400 text-center mt-6 text-lg font-light">
                        La foto anterior se eliminará y, en su lugar, se usará esta imagen.
                    </p>
                </div>
                <div class="flex justify-between mx-4 lg:mx-20">
                    <a class="text-blue-700 hover:text-blue-800 py-2 px-4 rounded-full border border-blue-700 hover:border-blue-800 flex items-center justify-center"
                       href="{% url 'profiles:auth_update_profile' %}">
                        <i class="fa-solid fa-file-pen mr-2"></i> Cancelar
                    </a>

                    <button type="submit"
                            class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full flex items-center justify-center">
                        <i class="fa-solid fa-eraser mr-2"></i> Eliminar
                    </button>
                </div>
            </div>
        </div>
    </form>
</section>

{% endblock content %}

core/profiles/templates/ss.html
<form method="post" action="{% url 'profiles:auth_remove_image' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar Foto de Perfil</button>
</form>


<div class="card">
    <div class="image-container">
        <img src="foto-actual.jpg" alt="Foto de perfil actual">
    </div>
    <div class="arrow">
        →
    </div>
    <div class="image-container">
        <img src="foto-nueva.jpg" alt="Foto de perfil predeterminada">
    </div>
    <div class="text">
        ¿Quieres quitar la foto de perfil?
        <p>
            La foto anterior se eliminará y, en su lugar, se usará esta imagen.
        </p>
        <button class="cancel">Cancelar</button>
        <button class="quitar">Quitar</button>
    </div>
</div>