config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.home.views import HomeTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeTemplateView.as_view(), name='home'),
    path('home/', include('core.home.urls')),
    path('profil/', include('core.profiles.urls')),
    path('chatbot/', include('core.chatbot.urls')),
    path('auth/', include('core.login_register.urls')),
    path('authRercPassw/', include('core.recover_password.urls')),
    path('webscraping/', include('core.webscraping.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/login_register/urls.py
from django.urls import path
from . import views

app_name = "LoginRegister"
urlpatterns = [
    path('login/', views.signin, name="auth_login"),
    path('signup/', views.signup, name="auth_signup"),
    path('logout', views.signout, name='auth_logout'),
]

core/recover_password/urls.py
from django.urls import path
from . import views as v

app_name = "RecoverPassword"
urlpatterns = [
    path('reset_password/', v.CustomPasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', v.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', v.test_password_reset_link, name='test_reset_link'),
    path('reset/<uidb64>/<token>/', v.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', v.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password_reset/token_invalid/', v.TokenInvalidPasswordResetView.as_view(), name='password_reset_token_invalid'),

]

core/recover_password/models.py
from django.db import models

# Create your models here.

core/recover_password/views.py
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView
                                       )
from django.urls import reverse_lazy
from django.contrib.auth.forms import PasswordResetForm
# from app.security.models import User
from django.contrib import messages
from django.shortcuts import redirect
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from ..profiles.models import User





from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from django.http import HttpResponse
from ..profiles.models import User  # Ajusta la importación según tu proyecto

def test_password_reset_link(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        if default_token_generator.check_token(user, token):
            return HttpResponse("Token válido")
        else:
            return redirect('RecoverPassword:password_reset_token_invalid')
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        return HttpResponse("Token inválidoooooooo")

class CustomPasswordResetView(PasswordResetView):
    template_name = 'password_reset_form.html'
    email_template_name = 'password_reset_email.html'
    success_url = reverse_lazy('RecoverPassword:password_reset_done')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return super().form_valid(form)
        else:
            messages.error(self.request, "No hay una cuenta asociada con ese correo electrónico.")
            return redirect('RecoverPassword:reset_password')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'password_reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password_reset_confirm.html'
    success_url = reverse_lazy('RecoverPassword:password_reset_complete')

    # def dispatch(self, *args, **kwargs,):
    #     try:
    #         # Intenta decodificar el UID y validar el token
    #         uid = urlsafe_base64_decode(self.kwargs['uidb64']).decode()
    #         user = User.objects.get(pk=uid)
    #         if default_token_generator.check_token(user, self.kwargs['token']):
    #             print("!!!!!!!!!!!!!!!!!!")
    #             return super().dispatch(*args, **kwargs)
    #         else:
    #             print("WWWWWWWWWWWWWWWWWWWWWWWW")
    #             raise ValueError("Token inválido o expirado")
    #     except (TypeError, ValueError, OverflowError, User.DoesNotExist):
    #         # Si el token es inválido o ha expirado, muestra la plantilla de expiración
    #         return redirect('RecoverPassword:password_reset_token_invalid')
    #

    # def form_invalid(self, form):
    #     # Enviar un mensaje de error y redirigir a la página de token inválido
    #     messages.error(self.request, "El enlace de recuperación de contraseña es inválido o ha expirado.")
    #     return redirect('RecoverPassword:password_reset_token_invalid')
    #
    # def test_password_reset_link(self, request, uidb64, token):
    #     try:
    #         uid = force_str(urlsafe_base64_decode(uidb64))
    #         user = User.objects.get(pk=uid)
    #         if not default_token_generator.check_token(user, token):
    #             return redirect('RecoverPassword:password_reset_token_invalid')
    #     except (TypeError, ValueError, OverflowError, User.DoesNotExist):
    #         return redirect('RecoverPassword:password_reset_token_invalid')

class TokenInvalidPasswordResetView(PasswordResetView):
    template_name = 'password_reset_token_invalid.html'
    email_template_name = 'password_reset_email.html'
    success_url = reverse_lazy('RecoverPassword:password_reset_done')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return super().form_valid(form)
        else:
            messages.error(self.request, "No hay una cuenta asociada con ese correo electrónico.")
            return redirect('RecoverPassword:reset_password')

core/recover_password/templates/password_reset_complete.html
{% extends 'components/base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<div class="bg-slate-100 dark:bg-principal p-2 relative overflow-hidden">
    <div class="absolute inset-0 bg-center blur-[106px]"></div>
    <div class="relative">
        <section class="p-4 my-4 mx-auto max-w-4xl rounded-3xl bg-white dark:bg-secundario text-white" data-aos="fade-up" data-aos-delay="200">
            <h1 class="text-4xl text-center font-Pacifico dark:text-green-300 my-2">
                {{ title2 }}
            </h1>
            <div class="text-center my-4" data-aos="fade-right" data-aos-delay="200">
                <img src="{% static 'img/recuperar_contra_olvidada/contraexitoo.jpeg' %}" class="block w-20 md:w-64 lg:w-64 mx-auto rounded-full" alt="Signin">
            </div>
            <div class="flex justify-center items-center">
                <div class="max-w-sm text-center">
                    <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-100 mb-4">Contraseña restablecida</h2>
                    <p class="text-gray-600 dark:text-gray-300 mb-6">
                        Tu contraseña ha sido restablecida exitosamente. Ahora puedes
                        <a href="{% url 'home' %}" class="text-blue-500 hover:underline dark:text-blue-400">iniciar sesión</a>.
                    </p>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock content %}

{% block navbar %}
{% endblock navbar %}

core/recover_password/templates/password_reset_confirm.html
{% extends 'components/base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<div class="bg-slate-100 dark:bg-principal p-2 relative overflow-hidden">
    <div class="absolute inset-0 bg-center blur-[106px]"></div>
    <div class="relative">
        <section class="p-4 my-4 mx-auto max-w-4xl rounded-3xl bg-white dark:bg-secundario text-black dark:text-white" data-aos="fade-up" data-aos-delay="200">
            <h1 class="text-4xl text-center font-Pacifico text-gray-900 dark:text-green-300 my-2">
                {{ title2 }}
            </h1>

            <div class="flex justify-center items-center">
                <div class="max-w-sm w-full text-center">
                   <h2 class="text-2xl font-semibold text-green-500 dark:text-green-300 mb-4">Restablecer tu contraseña</h2>
                    <form method="post" class="bg-gray-100 dark:bg-gray-800 p-6 rounded-lg shadow-md">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="mb-4">
                            <label for="{{ form.new_password1.id_for_label }}" class="block text-gray-700 dark:text-gray-300 text-sm font-bold mb-2">{{ form.new_password1.label }}</label>
                            <input type="password" name="{{ form.new_password1.html_name }}" id="{{ form.new_password1.id_for_label }}" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 dark:text-white leading-tight focus:outline-none focus:shadow-outline bg-gray-200 dark:bg-gray-700" placeholder="Nueva contraseña" required>
                        </div>
                        <div class="mb-6">
                            <label for="{{ form.new_password2.id_for_label }}" class="block text-gray-700 dark:text-gray-300 text-sm font-bold mb-2">{{ form.new_password2.label }}</label>
                            <input type="password" name="{{ form.new_password2.html_name }}" id="{{ form.new_password2.id_for_label }}" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 dark:text-white leading-tight focus:outline-none focus:shadow-outline bg-gray-200 dark:bg-gray-700" placeholder="Confirmar nueva contraseña" required>
                        </div>
                        <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-4">Restablecer contraseña</button>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock content %}

{% block navbar %}
{% endblock navbar %}

core/recover_password/templates/password_reset_done.html
{% extends 'components/base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<div class="bg-slate-100 dark:bg-principal p-2 relative overflow-hidden">
    <div class="absolute inset-0 bg-center blur-[106px]"></div>
    <div class="relative">
        <section class="p-4 my-4 mx-auto max-w-4xl rounded-3xl bg-white dark:bg-secundario text-white" data-aos="fade-up" data-aos-delay="200">
            <h1 class="text-4xl text-center font-Pacifico dark:text-green-300 my-2">
                {{ title2 }}
            </h1>
            <div class="text-center my-4" data-aos="fade-right" data-aos-delay="200">
                <img src="{% static 'img/recuperar_contra_olvidada/ExitoCorreoEnviado.jpeg' %}" class="block w-20 md:w-64 lg:w-64 mx-auto rounded-full" alt="Signin">
            </div>
            <div class="flex justify-center items-center">
                <div class="max-w-sm text-center">
                    <h2 class="text-2xl font-bold text-green-500">Correo enviado</h2>
                    <p class="mt-4 text-lg text-gray-700 dark:text-gray-300">
                        Hemos enviado un correo electrónico con instrucciones para restablecer tu contraseña.
                    </p>
                    <a href="{% url 'LoginRegister:auth_login' %}" class="mt-6 inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Volver al inicio de sesión
                    </a>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock content %}

{% block navbar %}
{% endblock navbar %}

core/recover_password/templates/password_reset_email.html
{% autoescape off %}
    Hola {{ user.username }},
    Para restablecer tu contraseña, haz clic en el enlace siguiente:
    {{ protocol }}://{{ domain }}{% url 'RecoverPassword:password_reset_confirm' uidb64=uid token=token %}
    Si no solicitaste este cambio, puedes ignorar este correo electrónico.
    Gracias.
    Tu equipo,
    🔗 Cucho Store 🔗
{% endautoescape %}

core/recover_password/templates/password_reset_form.html
{% extends 'components/base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<div class="bg-slate-100 dark:bg-principal p-2 relative overflow-hidden">
    <div class="absolute inset-0 bg-center blur-[106px]"></div>
    <div class="relative">
        <section class="p-4 my-4 mx-auto max-w-4xl rounded-3xl bg-white dark:bg-secundario text-gray-800 dark:text-white" data-aos="fade-up" data-aos-delay="200">
            <h1 class="text-4xl text-center font-Pacifico text-gray-900 dark:text-green-300 my-2">
                {{ title2 }}
            </h1>
            <p class="text-center my-6 font-black my-2 text-2xl text-gray-800 dark:text-gray-400 uppercase">
                ¡Bienvenido de vuelta!
            </p>
            <div class="text-center my-4" data-aos="fade-right" data-aos-delay="200">
                <img src="{% static 'img/recuperar_contra_olvidada/recuperarContraseña.jpeg' %}" class="block w-20 md:w-64 lg:w-64 mx-auto rounded-full" alt="Signin">
            </div>
            <div class="flex justify-center items-center">
                <form method="post" class="max-w-sm">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label class="block text-gray-900 dark:text-white text-sm font-bold mb-2" for="email">
                            Correo Electrónico
                        </label>
                        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 dark:text-white leading-tight focus:outline-none focus:shadow-outline bg-gray-200 dark:bg-gray-800" id="email" name="email" type="email" placeholder="Correo Electrónico">
                    </div>
                    <div class="flex items-center justify-between">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Recuperar Contraseña</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>
{% endblock content %}

{% block navbar %}
{% endblock navbar %}

core/recover_password/templates/password_reset_token_invalid.html
{% extends 'components/base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<div class="bg-slate-100 dark:bg-principal p-2 relative overflow-hidden">
    <div class="absolute inset-0 bg-center blur-[106px]"></div>
    <div class="relative">
        <section class="p-4 my-4 mx-auto max-w-4xl rounded-3xl bg-white dark:bg-secundario text-white" data-aos="fade-up" data-aos-delay="200">
            <h1 class="text-4xl text-center font-Pacifico dark:text-green-300 my-2">
                {{ title2 }}
            </h1>
            <p class="text-center my-6 font-black text-2xl dark:text-gray-400 uppercase text-white">Lo sentimos, el enlace para recuperar la contraseña ha expirado.</p>
            <div class="text-center my-4" data-aos="fade-right" data-aos-delay="200">
                <img src="{% static 'img/recuperar_contra_olvidada/logo_recuperar_contra.jpeg' %}" class="block w-20 md:w-64 lg:w-64 mx-auto rounded-full" alt="Recuperar contraseña">
            </div>
            <div class="flex justify-center items-center">
                <form method="post" class="max-w-sm">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label class="block text-white text-sm font-bold mb-2" for="email">
                            Ingrese su correo electrónico para enviar un nuevo enlace de recuperación:
                        </label>
                        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline bg-gray-800 text-white" id="email" name="email" type="email" placeholder="Correo Electrónico" required>
                    </div>
                    <div class="flex items-center justify-between">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Enviar nuevo enlace</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>
{% endblock content %}

{% block navbar %}
{% endblock navbar %}