config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.home.views import HomeTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeTemplateView.as_view(), name='home'),
    path('home/', include('core.home.urls')),
    path('profil/', include('core.profiles.urls')),
    path('chatbot/', include('core.chatbot.urls')),
    path('auth/', include('core.login_register.urls')),
    path('authRercPassw/', include('core.recover_password.urls')),
    path('webscraping/', include('core.webscraping.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/login_register/urls.py
from django.urls import path
from . import views

app_name = "LoginRegister"
urlpatterns = [
    path('login/', views.signin, name="auth_login"),
    path('signup/', views.signup, name="auth_signup"),
    path('logout', views.signout, name='auth_logout'),
]

core/recover_password/urls.py
from django.urls import path
from . import views as v

app_name = "RecoverPassword"
urlpatterns = [
    path('reset_password/', v.CustomPasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', v.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', v.test_password_reset_link, name='test_reset_link'),
    path('reset/<uidb64>/<token>/', v.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', v.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password_reset/token_invalid/', v.TokenInvalidPasswordResetView.as_view(), name='password_reset_token_invalid'),

]

core/login_register/models.py
from django.db import models

# Create your models here.

core/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    # gender = models.CharField(verbose_name='Sexo',
    #                           max_length=1,
    #                           choices=(('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro Genero')),
    #                           blank=False, null=False)

    image = models.ImageField(
        verbose_name='Archive image',
        upload_to='users/',
        max_length=1024,
        blank=True,
        null=True
    )
    email = models.EmailField(verbose_name='Email', unique=True)
    USERNAME_FIELD = "email"  # cambia el login
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    def __str__(self):
        return '{}'.format(self.username)

    @property
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_image(self):
        if self.image:
            return self.image.url
        else:
            return '/static/img/usuario_anonimo.png'

core/login_register/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from ..profiles.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from ..profiles.forms import CustomUserCreationForm,CustomUserUpdateForm

# Cerrar Sesión
@login_required
def signout(request):
    logout(request)
    return redirect("home")

# Registro de Usuarios
def signup(request):
    data = {"title1": "IC - Registro", "title2": "Registro de Usuarios"}

    if request.method == "GET":
        # Renderiza el formulario vacío en caso de GET
        return render(request, "signup.html", {"form": CustomUserCreationForm, **data})
    else:
        # Procesa el formulario enviado por POST
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            # Si el formulario es válido, guarda el usuario y muestra un mensaje de éxito
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,
                             f"Bienvenido {username}, tu cuenta ha sido creada exitosamente. Inicia sesión para continuar.")
            return redirect("LoginRegister:auth_login")  # Redirige a la página de inicio de sesión
        else:
            # Si hay errores en el formulario, muestra el formulario con los errores
            messages.error(request, "Error al registrar el usuario. Por favor, revisa los datos ingresados.")
            return render(request, "signup.html", {"form": form, **data})


# Iniciar Sesión
def signin(request):
    data = {"title1": "IC - Login", "title2": "Inicio de Sesión"}

    if request.method == "GET":
        success_messages = messages.get_messages(request)
        return render(request, "signin.html",
                      {"form": AuthenticationForm(), "success_messages": success_messages, **data})
    else:
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
            else:
                messages.error(request, "El usuario o la contraseña son incorrectos")
        return render(request, "signin.html", {"form": form, "error": "Datos inválidos", **data})

core/login_register/templates/signin.html
{% extends 'components/base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<style>
    footer {
        display: none;
    }
</style>
<!-- Include Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">
<div class="bg-gray-100 flex h-screen">
    <!-- Left: Image -->
    <div class="w-7/10 h-screen hidden lg:block">
        <img src="{% static 'img/hero1.jpg' %}" alt="Signin" class="object-cover w-full h-full">
    </div>
    <!-- Right: Login Form -->
    <div class="w-full lg:w-3/10 flex items-center justify-center lg:p-36 md:p-24 p-8 bg-white dark:bg-principal">
        <div class="w-full max-w-md bg-white dark:bg-black p-8 rounded-lg shadow-lg">
            <h1 class="text-3xl font-semibold mb-6 text-orange-500 dark:text-orange-300">{{ title2 }}</h1>
            <p class="text-center my-4 font-bold text-xl text-gray-700 dark:text-gray-300 uppercase">¡Bienvenido de vuelta!</p>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Username Input -->
                <div class="mb-4">
                    <label for="id_username" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.username.label }}</label>
                    <input type="text" id="id_username" name="username" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500" placeholder="{{ form.username.label }}" required autocomplete="off">
                </div>
                <!-- Password Input -->
                <div class="mb-4 relative">
                    <label for="id_password" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.password.label }}</label>
                    <div class="relative">
                        <input type="password" id="id_password" name="password" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500 pr-10" placeholder="{{ form.password.label }}" required autocomplete="off">
                        <button type="button" id="togglePassword" class="absolute inset-y-0 right-0 flex items-center pr-3 top-2">
                            <i class="fas fa-eye text-gray-500 dark:text-gray-300"></i>
                        </button>
                    </div>
                </div>
                <!-- Remember Me Checkbox -->
                <div class="mb-4 flex items-center">
                    <input type="checkbox" id="remember" name="remember" class="text-orange-500">
                    <label for="remember" class="text-gray-600 dark:text-gray-200 ml-2">Remember Me</label>
                </div>
                <!-- Forgot Password Link -->
                <div class="mb-6 text-blue-500 dark:text-blue-300">
                    <a href="{% url 'RecoverPassword:reset_password' %}" class="hover:underline">¿No recuerdas tu contraseña?</a>
                </div>
                <!-- Login Button -->
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 dark:bg-orange-500 dark:hover:bg-orange-600 text-white font-semibold rounded-md py-2 px-4 w-full">Iniciar Sesión</button>
            </form>
            <!-- Sign up Link -->
            <div class="mt-6 text-blue-500 dark:text-orange-300 text-center font-poppins text-lg font-bold">
                <a href="{% url 'LoginRegister:auth_signup' %}" class="hover:underline">Regístrate</a>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>
<script>
    document.getElementById("togglePassword").addEventListener("click", function () {
        var passwordInput = document.getElementById("id_password");
        var icon = this.querySelector("i");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            icon.classList.remove("fa-eye");
            icon.classList.add("fa-eye-slash");
        } else {
            passwordInput.type = "password";
            icon.classList.remove("fa-eye-slash");
            icon.classList.add("fa-eye");
        }
    });
</script>
{% endblock content %}
{% block navbar %}
{% endblock navbar %}

core/login_register/templates/signup.html
{% extends 'components/base.html' %}
{% load static %}

{% block content %}
<title>{% block title %} {{ title1 }} {% endblock title %}</title>
<style>
    footer {
        display: none;
    }
</style>
<!-- Include Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">

<div class="bg-gray-100 flex h-screen flex-row-reverse">
    <!-- Right: Image -->
    <div class="w-7/10 h-screen hidden lg:block">
        <img src="{% static 'img/hero32.jpeg' %}" alt="Signin" class="object-cover w-full h-full">
    </div>
    <!-- Left: Registration Form -->
    <div class="w-full lg:w-3/10 flex items-center justify-center lg:p-36 md:p-24 p-8 bg-white dark:bg-principal">
        <div class="w-full max-w-4xl bg-white dark:bg-black p-8 rounded-lg shadow-lg">
            <h1 class="text-3xl font-semibold mb-6 text-orange-500 dark:text-orange-300">{{ title2 }}</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                    <!-- Username -->
                    <div class="mb-4">
                        <label for="id_username" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.username.label }}</label>
                        <input type="text" id="id_username" name="username" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500" value="{{ form.username.value|default_if_none:'' }}" placeholder="{{ form.username.label }}" required>
                    </div>
                    <!-- First Name -->
                    <div class="mb-4">
                        <label for="id_first_name" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.first_name.label }}</label>
                        <input type="text" id="id_first_name" name="first_name" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500" value="{{ form.first_name.value|default_if_none:'' }}" placeholder="{{ form.first_name.label }}" required>
                    </div>
                    <!-- Last Name -->
                    <div class="mb-4">
                        <label for="id_last_name" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.last_name.label }}</label>
                        <input type="text" id="id_last_name" name="last_name" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500" value="{{ form.last_name.value|default_if_none:'' }}" placeholder="{{ form.last_name.label }}" required>
                    </div>
                    <!-- Email -->
                    <div class="mb-4">
                        <label for="id_email" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.email.label }}</label>
                        <input type="email" id="id_email" name="email" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500" value="{{ form.email.value|default_if_none:'' }}" placeholder="{{ form.email.label }}" required>
                    </div>
                </div>
                <!-- Password Fields -->
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                    <!-- Password -->
                    <div class="mb-4 relative">
                        <label for="id_password1" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.password1.label }}</label>
                        <div class="relative">
                            <input type="password" id="id_password1" name="password1" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500 pr-10" placeholder="{{ form.password1.label }}" required autocomplete="off">
                            <!-- Ícono de 'ojo' dentro del campo input -->
                            <button type="button" id="togglePassword1" aria-label="Mostrar contraseña" class="absolute inset-y-0 right-3 flex items-center">
                                <i class="fa fa-eye text-gray-600"></i>
                            </button>
                        </div>
                    </div>
                    <!-- Confirm Password -->
                    <div class="mb-4 relative">
                        <label for="id_password2" class="block text-blue-500 dark:text-blue-300 font-poppins text-lg font-bold">{{ form.password2.label }}</label>
                        <div class="relative">
                            <input type="password" id="id_password2" name="password2" class="w-full border border-gray-300 rounded-md py-2 px-3 text-gray-900 dark:bg-principal dark:border-gray-600 dark:text-white focus:outline-none focus:border-orange-500 pr-10" placeholder="{{ form.password2.label }}" required autocomplete="off">
                            <!-- Ícono de 'ojo' dentro del campo input -->
                            <button type="button" id="togglePassword2" aria-label="Mostrar contraseña" class="absolute inset-y-0 right-3 flex items-center">
                                <i class="fa fa-eye text-gray-600"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <!-- Submit Button -->
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 dark:bg-orange-500 dark:hover:bg-orange-600 text-white font-semibold rounded-md py-2 px-4 w-full mt-4">Registrarse</button>
            </form>
            <p class="text-blue-500 dark:text-orange-300 text-center mt-3">
                ¿Ya tienes una cuenta? <a href="{% url 'LoginRegister:auth_login' %}" class="hover:underline">Inicia Sesión</a>
            </p>
        </div>
    </div>
</div>

<script>
    function togglePasswordVisibility(inputId, buttonId) {
        const input = document.getElementById(inputId);
        const button = document.getElementById(buttonId);
        const icon = button.querySelector("i");

        // Cambiar entre mostrar/ocultar la contraseña
        button.addEventListener("click", function () {
            if (input.type === "password") {
                input.type = "text";
                icon.classList.remove("fa-eye");
                icon.classList.add("fa-eye-slash");
            } else {
                input.type = "password";
                icon.classList.remove("fa-eye-slash");
                icon.classList.add("fa-eye");
            }
        });
    }

    // Inicializar los campos de contraseña
    togglePasswordVisibility("id_password1", "togglePassword1");
    togglePasswordVisibility("id_password2", "togglePassword2");
</script>
{% endblock content %}

{% block navbar %}
{% endblock navbar %}